version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: dockerfile
    container_name: web-chat-app
    ports:
      - "80:80"
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
